name: haus.chris.nringest
protocol_version: 1
description: Add config files as NR Inventory
os: linux
commands:
  inventory:
    command:
      - ./config-ohi
      - --inventory
    prefix: my/prefix
